divine_rapier_ai_translator:
  divine_rapier_ai_translator_enabled:
    default: false
    client: true

  divine_rapier_ai_translator_preset_model:
    type: enum
    default: "gpt-4o"
    choices:
      - gpt-5
      - gpt-5-mini
      - gpt-5-nano
      - gpt-4o
      - gpt-4o-mini
      - gpt-3.5-turbo
      - grok-4
      - grok-4-fast-non-reasoning
      - grok-3
      - grok-2
      - deepseek-r1
      - deepseek-v3
      - custom
    client: true

  divine_rapier_ai_translator_auto_translate_languages:
    default: "zh-cn,en,es"
    client: true

  # API Keys for different providers
  divine_rapier_ai_translator_openai_api_key:
    default: ""
    secret: true

  divine_rapier_ai_translator_xai_api_key:
    default: ""
    secret: true

  divine_rapier_ai_translator_deepseek_api_key:
    default: ""
    secret: true

  # Custom model settings (only used when preset_model is "custom")
  divine_rapier_ai_translator_custom_model_name:
    default: ""
    client: true

  divine_rapier_ai_translator_custom_base_url:
    default: ""
    client: false

  divine_rapier_ai_translator_custom_api_key:
    default: ""
    secret: true

  divine_rapier_ai_translator_custom_max_tokens:
    default: 16000
    min: 100
    max: 200000
    client: false

  divine_rapier_ai_translator_custom_max_output_tokens:
    default: 4096
    min: 100
    max: 32000
    client: false

  divine_rapier_ai_translator_rate_limit_per_minute:
    default: 60
    min: 1
    max: 1000

  divine_rapier_ai_translator_max_content_length:
    default: 4000
    min: 100
    max: 100000

  divine_rapier_ai_translator_preserve_formatting:
    default: true
    client: true

  divine_rapier_ai_translator_translate_title:
    default: true
    client: true